// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Util$ReasonTrainer = require("./Util.bs.js");

var component = ReasonReact.statelessComponent("Button");

function make(onClick, $staropt$star, text, $staropt$star$1, _) {
  var disabled = $staropt$star !== undefined ? $staropt$star : false;
  var big = $staropt$star$1 !== undefined ? $staropt$star$1 : true;
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("button", {
                          className: "button is-primary is-fullwidth " + (
                            big ? "is-large" : ""
                          ),
                          disabled: disabled,
                          onClick: onClick
                        }, Util$ReasonTrainer.text(text));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
