// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_format = require("bs-platform/lib/js/caml_format.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Input$ReasonTrainer = require("./Input.bs.js");
var Button$ReasonTrainer = require("./Button.bs.js");

var component = ReasonReact.reducerComponent("Create-exercise");

function initialState() {
  return /* record */[
          /* name */"",
          /* series : [] */0,
          /* rest */30,
          /* completed */0
        ];
}

function make(onSubmit, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var send = param[/* send */3];
              var state = param[/* state */1];
              return React.createElement("div", undefined, ReasonReact.element(undefined, undefined, Input$ReasonTrainer.make((function (value) {
                                    return Curry._1(send, /* UpdateName */Block.__(0, [value]));
                                  }), /* Text */0, state[/* name */0], "Exercise name", /* array */[])), ReasonReact.element(undefined, undefined, Input$ReasonTrainer.make((function (value) {
                                    return Curry._1(send, /* UpdateRest */Block.__(1, [value]));
                                  }), /* Number */1, String(state[/* rest */2]), "Resting", /* array */[])), ReasonReact.element(undefined, undefined, Button$ReasonTrainer.make((function () {
                                    return Curry._1(send, /* Submit */0);
                                  }), undefined, "+Exercise", undefined, /* array */[])));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* name */"",
                      /* series : [] */0,
                      /* rest */30,
                      /* completed */0
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                return /* UpdateWithSideEffects */Block.__(2, [
                          /* record */[
                            /* name */"",
                            /* series : [] */0,
                            /* rest */30,
                            /* completed */0
                          ],
                          (function () {
                              return Curry._1(onSubmit, state);
                            })
                        ]);
              } else if (action.tag) {
                return /* Update */Block.__(0, [/* record */[
                            /* name */state[/* name */0],
                            /* series */state[/* series */1],
                            /* rest */Caml_format.caml_int_of_string(action[0]),
                            /* completed */state[/* completed */3]
                          ]]);
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* name */action[0],
                            /* series */state[/* series */1],
                            /* rest */state[/* rest */2],
                            /* completed */state[/* completed */3]
                          ]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.initialState = initialState;
exports.make = make;
/* component Not a pure module */
