// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Util$ReasonTrainer = require("./Util.bs.js");
var Input$ReasonTrainer = require("./Input.bs.js");
var Button$ReasonTrainer = require("./Button.bs.js");
var Trainer$ReasonTrainer = require("./Trainer.bs.js");
var CreateSession$ReasonTrainer = require("./CreateSession.bs.js");

var component = ReasonReact.reducerComponent("Create-table");

function initialState() {
  return /* record */[
          /* sessions : [] */0,
          /* name */"",
          /* completed */0
        ];
}

function make(send, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var ssend = param[/* send */3];
              var state = param[/* state */1];
              return React.createElement("div", undefined, ReasonReact.element(undefined, undefined, Input$ReasonTrainer.make((function (value) {
                                    return Curry._1(ssend, /* UpdateName */Block.__(0, [value]));
                                  }), /* Text */0, state[/* name */1], "Table name", /* array */[])), ReasonReact.element(undefined, undefined, CreateSession$ReasonTrainer.make((function (session) {
                                    return Curry._1(ssend, /* AddSession */Block.__(1, [session]));
                                  }), /* array */[])), Util$ReasonTrainer.text(Json.stringify(Trainer$ReasonTrainer.Encode[/* table */2](state))), ReasonReact.element(undefined, undefined, Button$ReasonTrainer.make((function () {
                                    return Curry._1(ssend, /* Submit */0);
                                  }), undefined, "Save table", undefined, /* array */[])));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* sessions : [] */0,
                      /* name */"",
                      /* completed */0
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                return /* SideEffects */Block.__(1, [(function () {
                              return Curry._1(send, /* AddTable */Block.__(2, [state]));
                            })]);
              } else if (action.tag) {
                return /* Update */Block.__(0, [/* record */[
                            /* sessions : :: */[
                              action[0],
                              state[/* sessions */0]
                            ],
                            /* name */state[/* name */1],
                            /* completed */state[/* completed */2]
                          ]]);
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* sessions */state[/* sessions */0],
                            /* name */action[0],
                            /* completed */state[/* completed */2]
                          ]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.initialState = initialState;
exports.make = make;
/* component Not a pure module */
