// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Json = require("@glennsl/bs-json/src/Json.bs.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Util$ReasonTrainer = require("./Util.bs.js");
var Input$ReasonTrainer = require("./Input.bs.js");
var Button$ReasonTrainer = require("./Button.bs.js");
var Trainer$ReasonTrainer = require("./Trainer.bs.js");
var CreateExercise$ReasonTrainer = require("./CreateExercise.bs.js");

var component = ReasonReact.reducerComponent("Create-session");

function initialState() {
  return /* record */[
          /* name */"",
          /* exercises : [] */0
        ];
}

function listExercises(ex) {
  return Util$ReasonTrainer.text(Json.stringify(Json_encode.list(Trainer$ReasonTrainer.Encode[/* exercise */0], ex)));
}

function make(onSubmit, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (param) {
              var ssend = param[/* send */3];
              var state = param[/* state */1];
              return React.createElement("div", undefined, ReasonReact.element(undefined, undefined, Input$ReasonTrainer.make((function (value) {
                                    return Curry._1(ssend, /* UpdateName */Block.__(0, [value]));
                                  }), /* Text */0, state[/* name */0], "Session Name", /* array */[])), ReasonReact.element(undefined, undefined, CreateExercise$ReasonTrainer.make((function (exercise) {
                                    return Curry._1(ssend, /* AddExercise */Block.__(1, [exercise]));
                                  }), /* array */[])), listExercises(state[/* exercises */1]), ReasonReact.element(undefined, undefined, Button$ReasonTrainer.make((function () {
                                    return Curry._1(ssend, /* Submit */0);
                                  }), undefined, "Save session", undefined, /* array */[])));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* name */"",
                      /* exercises : [] */0
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (typeof action === "number") {
                return /* UpdateWithSideEffects */Block.__(2, [
                          /* record */[
                            /* name */"",
                            /* exercises : [] */0
                          ],
                          (function () {
                              return Curry._1(onSubmit, state);
                            })
                        ]);
              } else if (action.tag) {
                return /* Update */Block.__(0, [/* record */[
                            /* name */state[/* name */0],
                            /* exercises : :: */[
                              action[0],
                              state[/* exercises */1]
                            ]
                          ]]);
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* name */action[0],
                            /* exercises */state[/* exercises */1]
                          ]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.initialState = initialState;
exports.listExercises = listExercises;
exports.make = make;
/* component Not a pure module */
