// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';


var press_banca = /* record */[
  /* name */"Press de banca",
  /* series : :: */[
    10,
    /* :: */[
      8,
      /* :: */[
        8,
        /* :: */[
          6,
          /* :: */[
            6,
            /* [] */0
          ]
        ]
      ]
    ]
  ],
  /* rest */3,
  /* completed */0
];

var press_hombro = /* record */[
  /* name */"Press de hombro",
  /* series : :: */[
    10,
    /* :: */[
      10,
      /* :: */[
        8,
        /* :: */[
          8,
          /* :: */[
            6,
            /* [] */0
          ]
        ]
      ]
    ]
  ],
  /* rest */1,
  /* completed */0
];

var dale_000 = /* sessions : :: */[
  /* record */[
    /* name */"Day 1",
    /* exercises : :: */[
      press_hombro,
      /* [] */0
    ]
  ],
  /* :: */[
    /* record */[
      /* name */"Day 2",
      /* exercises : :: */[
        press_banca,
        /* :: */[
          press_hombro,
          /* [] */0
        ]
      ]
    ],
    /* [] */0
  ]
];

var dale = /* record */[
  dale_000,
  /* name */"Prueba",
  /* completed */0
];

exports.press_banca = press_banca;
exports.press_hombro = press_hombro;
exports.dale = dale;
/* No side effect */
