// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Util$ReasonTrainer = require("./Util.bs.js");
var Store$ReasonTrainer = require("./Store.bs.js");
var Table$ReasonTrainer = require("./Table.bs.js");
var Button$ReasonTrainer = require("./Button.bs.js");

(( require("./styles.scss") ));

var stateDev = ( require("./tabla") );

function listTables(tables, onClick) {
  return Util$ReasonTrainer.listToComponent((function (table) {
                return ReasonReact.element(table[/* name */1], undefined, Button$ReasonTrainer.make((function () {
                                  return Curry._1(onClick, table);
                                }), undefined, table[/* name */1], undefined, /* array */[]));
              }), tables);
}

Store$ReasonTrainer.update((function () {
        return Store$ReasonTrainer.Decode[/* state */1](stateDev);
      }));

ReactDOMRe.renderToElementWithId(Store$ReasonTrainer.render((function (state) {
            var match = state[/* table */0];
            if (match !== undefined) {
              return ReasonReact.element(undefined, undefined, Table$ReasonTrainer.make(match, /* array */[]));
            } else {
              return listTables(state[/* tables */1], (function (table) {
                            var partial_arg = table[/* name */1];
                            return Store$ReasonTrainer.update((function (param) {
                                          return Store$ReasonTrainer.selectTable(partial_arg, param);
                                        }));
                          }));
            }
          })), "index1");

exports.stateDev = stateDev;
exports.listTables = listTables;
/*  Not a pure module */
