// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Input");

function handleChange(fn, evt) {
  return Curry._1(fn, evt.target.value);
}

function make(onChange, $staropt$star, value, $staropt$star$1, _) {
  var type_ = $staropt$star !== undefined ? $staropt$star : /* Text */0;
  var placeholder = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  var handler = function (param) {
    return Curry._1(onChange, param.target.value);
  };
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              if (type_) {
                return React.createElement("input", {
                            className: "input",
                            placeholder: placeholder,
                            type: "number",
                            value: value,
                            onChange: handler
                          });
              } else {
                return React.createElement("input", {
                            className: "input",
                            placeholder: placeholder,
                            type: "text",
                            value: value,
                            onChange: handler
                          });
              }
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.handleChange = handleChange;
exports.make = make;
/* component Not a pure module */
