// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var RunExercise$ReactTemplate = require("./RunExercise.bs.js");

var component = ReasonReact.reducerComponent("Session");

function shift(session) {
  return /* record */[
          /* session */List.tl(session),
          /* current */List.hd(session)
        ];
}

function make(session, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return ReasonReact.element(undefined, undefined, RunExercise$ReactTemplate.make(self[/* state */1][/* current */1], (function () {
                                return Curry._1(self[/* send */3], /* Next */0);
                              }), /* array */[]));
            }),
          /* initialState */(function () {
              return shift(session[/* exercises */1]);
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (_, state) {
              return /* Update */Block.__(0, [shift(state[/* session */0])]);
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.shift = shift;
exports.make = make;
/* component Not a pure module */
