// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var RunExercise$ReactTemplate = require("./RunExercise.bs.js");

var component = ReasonReact.reducerComponent("Session");

function shift(session) {
  return /* record */[
          /* session */List.tl(session),
          /* current */List.hd(session)
        ];
}

function extendSlice(finished, param) {
  return /* record */[
          /* session */param[/* session */0],
          /* current */param[/* current */1],
          /* finished */finished
        ];
}

function update(state) {
  var exercises = state[/* session */0];
  if (exercises) {
    return extendSlice(false, shift(exercises));
  } else {
    return /* record */[
            /* session */state[/* session */0],
            /* current */state[/* current */1],
            /* finished */true
          ];
  }
}

function make(session, onComplete, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */(function () {
              return extendSlice(false, shift(session[/* exercises */1]));
            }),
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = !self[/* state */1][/* finished */2];
              if (match) {
                return ReasonReact.element(undefined, undefined, RunExercise$ReactTemplate.make(self[/* state */1][/* current */1], (function () {
                                  return Curry._1(self[/* send */3], /* Next */0);
                                }), /* array */[]));
              } else {
                return React.createElement("button", {
                            onClick: (function () {
                                return Curry._1(self[/* send */3], /* Finish */1);
                              })
                          }, "Finish session");
              }
            }),
          /* initialState */(function () {
              return extendSlice(false, shift(session[/* exercises */1]));
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (action) {
                Curry._1(onComplete, session[/* name */0]);
                return /* NoUpdate */0;
              } else {
                return /* Update */Block.__(0, [update(state)]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.shift = shift;
exports.extendSlice = extendSlice;
exports.update = update;
exports.make = make;
/* component Not a pure module */
