// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Hero$ReactTemplate = require("./Hero.bs.js");
var Util$ReactTemplate = require("./Util.bs.js");
var Session$ReactTemplate = require("./Session.bs.js");

var component = ReasonReact.reducerComponent("Session");

function listSessions(sessions, onClick) {
  return Util$ReactTemplate.listToComponent((function (session) {
                return React.createElement("button", {
                            key: session[/* name */0],
                            className: "button is-primary is-fullwidth is-outlined",
                            onClick: (function () {
                                return Curry._1(onClick, session);
                              })
                          }, Util$ReactTemplate.text(session[/* name */0]));
              }), sessions);
}

function make(table, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */1][/* session */0];
              return React.createElement("div", {
                          className: "column"
                        }, match ? ReasonReact.element(undefined, undefined, Session$ReactTemplate.make(match[0], (function () {
                                      return Curry._1(self[/* send */3], /* Finish */0);
                                    }), /* array */[])) : React.createElement("div", undefined, ReasonReact.element(undefined, undefined, Hero$ReactTemplate.make(/* array */[React.createElement("p", {
                                              className: "title is-2"
                                            }, Util$ReactTemplate.text(table[/* name */1]))])), listSessions(table[/* sessions */0], (function (session) {
                                      return Curry._1(self[/* send */3], /* Select */[session]);
                                    }))));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* session : NotSelected */0,
                      /* sessions */table[/* sessions */0]
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              if (action) {
                var session = action[0];
                console.log(session);
                return /* Update */Block.__(0, [/* record */[
                            /* session : Selected */[session],
                            /* sessions */state[/* sessions */1]
                          ]]);
              } else {
                return /* Update */Block.__(0, [/* record */[
                            /* session : NotSelected */0,
                            /* sessions */state[/* sessions */1]
                          ]]);
              }
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.listSessions = listSessions;
exports.make = make;
/* component Not a pure module */
