// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Json_encode = require("@glennsl/bs-json/src/Json_encode.bs.js");

function exercise(param) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "name",
                param[/* name */0]
              ],
              /* :: */[
                /* tuple */[
                  "reps",
                  param[/* reps */1]
                ],
                /* :: */[
                  /* tuple */[
                    "rest",
                    param[/* rest */3]
                  ],
                  /* :: */[
                    /* tuple */[
                      "series",
                      param[/* series */2]
                    ],
                    /* :: */[
                      /* tuple */[
                        "completed",
                        param[/* completed */4]
                      ],
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]);
}

function session(param) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "name",
                param[/* name */0]
              ],
              /* :: */[
                /* tuple */[
                  "exercises",
                  Json_encode.list(exercise, param[/* exercises */1])
                ],
                /* [] */0
              ]
            ]);
}

function table(param) {
  return Json_encode.object_(/* :: */[
              /* tuple */[
                "name",
                param[/* name */1]
              ],
              /* :: */[
                /* tuple */[
                  "completed",
                  param[/* completed */2]
                ],
                /* :: */[
                  /* tuple */[
                    "sessions",
                    Json_encode.list(session, param[/* sessions */0])
                  ],
                  /* [] */0
                ]
              ]
            ]);
}

var Encode = /* module */[
  /* exercise */exercise,
  /* session */session,
  /* table */table
];

var entrena_puto = /* record */[
  /* name */"Press de banca",
  /* reps */10,
  /* series */5,
  /* rest */30,
  /* completed */0
];

var dale_000 = /* sessions : :: */[
  /* record */[
    /* name */"D\xc3\xada 2",
    /* exercises : :: */[
      entrena_puto,
      /* [] */0
    ]
  ],
  /* [] */0
];

var dale = /* record */[
  dale_000,
  /* name */"Prueba",
  /* completed */0
];

function isCompleted(exercise) {
  return exercise[/* series */2] === exercise[/* completed */4];
}

function newTable(name) {
  return /* record */[
          /* sessions : [] */0,
          /* name */name,
          /* completed */0
        ];
}

function newSession(name) {
  return /* record */[
          /* name */name,
          /* exercises : [] */0
        ];
}

function newExercise(name, reps, series, $staropt$star, _) {
  var rest = $staropt$star !== undefined ? $staropt$star : 30;
  return /* record */[
          /* name */name,
          /* reps */reps,
          /* series */series,
          /* rest */rest,
          /* completed */0
        ];
}

function insertExercise(session, exercise) {
  return /* record */[
          /* name */session[/* name */0],
          /* exercises : :: */[
            exercise,
            session[/* exercises */1]
          ]
        ];
}

function addToSession(table, sessionName, exercise) {
  return /* record */[
          /* sessions */List.map((function (session) {
                  var match = session[/* name */0] === sessionName;
                  if (match) {
                    return insertExercise(session, exercise);
                  } else {
                    return session;
                  }
                }), table[/* sessions */0]),
          /* name */table[/* name */1],
          /* completed */table[/* completed */2]
        ];
}

function addSession(table, session) {
  return /* record */[
          /* sessions : :: */[
            session,
            table[/* sessions */0]
          ],
          /* name */table[/* name */1],
          /* completed */table[/* completed */2]
        ];
}

var emptyTable = addToSession(addToSession(addToSession(addSession(/* record */[
                  /* sessions : [] */0,
                  /* name */"Rabo",
                  /* completed */0
                ], /* record */[
                  /* name */"No Existe",
                  /* exercises : [] */0
                ]), "No Existe", newExercise("Press anal", 10, 5, undefined, /* () */0)), "No Existe", newExercise("Press Brutal", 8, 5, undefined, /* () */0)), "No Existe", newExercise("Press Follamigo", 8, 5, 45, /* () */0));

var logDir = function (x){console.dir(x, {depth:12})};

logDir(table(emptyTable));

var puto = /* record */[
  /* name */"Press de banca",
  /* image */"./banca.png",
  /* category : Torso */3
];

exports.Encode = Encode;
exports.puto = puto;
exports.entrena_puto = entrena_puto;
exports.dale = dale;
exports.isCompleted = isCompleted;
exports.newTable = newTable;
exports.newSession = newSession;
exports.newExercise = newExercise;
exports.insertExercise = insertExercise;
exports.addToSession = addToSession;
exports.addSession = addSession;
exports.emptyTable = emptyTable;
exports.logDir = logDir;
/* emptyTable Not a pure module */
