// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");

var componentFromList = $$Array.of_list;

function text(str) {
  return str;
}

function textInt(i) {
  return String(i);
}

function listToComponent(fn, list) {
  return $$Array.of_list(List.map(fn, list));
}

exports.componentFromList = componentFromList;
exports.text = text;
exports.textInt = textInt;
exports.listToComponent = listToComponent;
/* No side effect */
